=begin
#Microsoft Bot Connector API - v3.0

#﻿The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector/Swagger/ConnectorAPI.json)    © 2016 Microsoft

OpenAPI spec version: v3
Contact: botframework@microsoft.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ConversationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConversationsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ConversationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConversationsApi' do
    it 'should create an instact of ConversationsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ConversationsApi)
    end
  end

  # unit tests for conversations_create_conversation
  # CreateConversation
  # Create a new Conversation.    POST to this method with a  * Bot being the bot creating the conversation  * IsGroup set to true if this is not a direct message (default is false)  * Members array contining the members you want to have be in the conversation.    The return value is a ResourceResponse which contains a conversation id which is suitable for use  in the message payload and REST API uris.    Most channels only support the semantics of bots initiating a direct message conversation.  An example of how to do that would be:    &#x60;&#x60;&#x60;  var resource &#x3D; await connector.conversations.CreateConversation(new ConversationParameters(){ Bot &#x3D; bot, members &#x3D; new ChannelAccount[] { new ChannelAccount(\&quot;user1\&quot;) } );  await connect.Conversations.SendToConversationAsync(resource.Id, new Activity() ... ) ;    &#x60;&#x60;&#x60;
  # @param parameters Parameters to create the conversation from
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_create_conversation test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_get_activity_members
  # GetActivityMembers
  # Call this method to enumerate the members of an activity.     This REST API takes a ConversationId and a ActivityId, returning an array of ChannelAccount[] objects   which are the members of the particular activity in the conversation.
  # @param conversation_id Conversation ID
  # @param activity_id Activity ID
  # @param [Hash] opts the optional parameters
  # @return [Array<ChannelAccount>]
  describe 'conversations_get_activity_members test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_get_conversation_members
  # GetConversationMembers
  # Call this method to enumerate the members of a converstion.     This REST API takes a ConversationId and returns an array of ChannelAccount[] objects   which are the members of the conversation.
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [Array<ChannelAccount>]
  describe 'conversations_get_conversation_members test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_reply_to_activity
  # 
  # 
  # @param conversation_id 
  # @param activity_id 
  # @param activity 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'conversations_reply_to_activity test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_send_to_conversation
  # SendToConversation
  # This method allows you to send a message to a conversation without refering to an activity.   This is useful to send an initial message to a conversation, or to add a message to the end of the conversation.
  # @param activity Activity to send
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'conversations_send_to_conversation test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for conversations_upload_attachment
  # UploadAttachment
  # This method allows you to upload an attachment directly into a channels blob storage.    This is useful because it allows you to store data in a compliant store when dealing with enterprises.    The response is a ResourceResponse which contains an AttachmentId which is suitable for using with the attachments api.
  # @param conversation_id Conversation ID
  # @param attachment_upload Attachment data
  # @param [Hash] opts the optional parameters
  # @return [ResourceResponse]
  describe 'conversations_upload_attachment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
