=begin
#Microsoft Bot Connector API - v3.0

#﻿The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector/Swagger/ConnectorAPI.json)    © 2016 Microsoft

OpenAPI spec version: v3
Contact: botframework@microsoft.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/api_response'
require 'swagger_client/models/activity'
require 'swagger_client/models/attachment'
require 'swagger_client/models/attachment_data'
require 'swagger_client/models/attachment_info'
require 'swagger_client/models/attachment_view'
require 'swagger_client/models/card_action'
require 'swagger_client/models/card_image'
require 'swagger_client/models/channel_account'
require 'swagger_client/models/conversation_account'
require 'swagger_client/models/conversation_parameters'
require 'swagger_client/models/entity'
require 'swagger_client/models/fact'
require 'swagger_client/models/geo_coordinates'
require 'swagger_client/models/hero_card'
require 'swagger_client/models/object'
require 'swagger_client/models/place'
require 'swagger_client/models/receipt_card'
require 'swagger_client/models/receipt_item'
require 'swagger_client/models/resource_response'
require 'swagger_client/models/signin_card'
require 'swagger_client/models/thumbnail_card'

# APIs
require 'swagger_client/api/attachments_api'
require 'swagger_client/api/conversations_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
